name: release

on:
  push:
    tags:
      - "v*"

jobs:

  # This job builds and uploads binary
  build-and-upload:
    name: build and upload release
    strategy:
      matrix:
        os: [macos, ubuntu]
    runs-on: ${{ matrix.os }}-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1

      # No need to install normal Java, you can build application only with GraalVM
      - name: setup GraalVM
        uses: DeLaGuardo/setup-graalvm@4.0
        with:
          graalvm: "21.0.0.2"
          java: "java11"
          arch: 'amd64'

      # (Optional) Install native-image
      - name: install native-image
        run: gu install native-image

      - name: cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: gradle-${{ matrix.os }}-${{ hashFiles('build.gradle') }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ matrix.os }}-

      # Builds native image
      - name: "build for ${{ matrix.os }}"
        run: ./gradlew nativeImage
        env:
          RUNNING_OS: ${{ matrix.os }}
          PROJECT_VERSION: ${{ steps.config.outputs.projectVersion }}

      # Uploads binary
      - name: upload ${{ matrix.os }} image
        uses: actions/upload-artifact@v2
        with:
          name: spotify-playlist-reverser-kt-${{ matrix.os }}
          path: build/bin/spotify-playlist-reverser-kt
